# Dependencies
markdown:         kramdown
highlighter:         true

# Permalinks
permalink:        pretty
# Allow specific dot-prefixed things per https://github.com/keybase/keybase-issues/issues/366
include: [".well-known"]

# Setup
title:            Josh
tagline:          '(the blog)'
description:      'Nerding it up, by <a href="//twitter.com/joahua">@joahua</a>.'
url:              https://josh.st
enforce_ssl:      josh.st

author:
  name:           'Josh Street'
  url:            //twitter.com/joahua

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/joahua/joshst

gems:
  - jekyll-feed
  - jekyll-paginate
  - redcarpet
