# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Josh
tagline:          '(the blog)'
description:      'Nerding it up, by <a href="//twitter.com/joahua">@joahua</a>.'
url:              http://josh.st

author:
  name:           'Josh Street'
  url:            //twitter.com/joahua

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/joahua/joshst
